### ISSUE TITLE
No licensing information

### ISSUE THREAD

**Issue by jcsalomon** [patrickmay/e-pluribus-hugo#1]
As suggested at http://sasquan.org/business-meeting/agenda/#open, an explicit open-source license is appropriate.

**Comment by patrickmay** [comment]
Thanks for the note.  I've added the MIT license to the repo.

**Comment by patrickmay** [comment]
```
Done.  Thanks for the note.
```

Regards,

Patrick

> On Aug 25, 2015, at 5:58 PM, Joel C. Salomon <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> As suggested at http://sasquan.org/business-meeting/agenda/#open http://sasquan.org/business-meeting/agenda/#open, an explicit open-source license is appropriate.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/patrickmay/e-pluribus-hugo/issues/1.

---

patrick@softwarematters.org mailto:patrick@softwarematters.org
Large scale, mission-critical, distributed OO systems design and implementation.
(C++, Java, Common Lisp, Jini, middleware, SOA)
